#config

#邮件发送主题
symbols = ["xrpusdt","dotusdt","linkusdt","ethusdt","eosusdt","ltcusdt","dogeusdt","adausdt","sushiusdt","uniusdt"]
amounts = [10,10,10,10,10,10,10,10,10,10,10]
stopProfit = [1.1,1.10,1.10,1.10,1.10,1.10,1.1,1.10,1.10,1.10,1.10]
triggerStopProfit = [1.09,1.09,1.09,1.09,1.09,1.09,1.09,1.09,1.09,1.09,1.09]

proxy = false
